name: 'CI'

on:
  push:
    branches: 
    - master 

jobs:
  all_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Packages'
      run: sudo apt update && sudo apt install libcunit1-dev gcovr libsdl2-dev
    - name: 'Compile'
      run: |
        mkdir BuildCI
        cd BuildCI
        cmake ../
        make
      #cmake --build .
    - name: 'Testing'
      run: |
        cd BuildCI
        chmod +x *
        ./mygame
      #ctest -V
    - name: 'Coverage'
      run: |
        cd BuildCI
        mkdir Coverage
        chmod +x *
        cd game
        ./test_pract1
        cd ..
        cd draw
        ./test_pract2
        cd ..
        make cover_html
    - uses: actions/upload-artifact@v1
      with:
        name: CoverageWeb
        path: BuildCI/Coverage



  
#   test_linux:
#     runs-on: ubuntu-latest
#     needs: build_linux
#     steps:
#       - uses: actions/download-artifact@v1
#         with:
#           name: binaries
#           path: BuildCI/
#       - name: 'Packages'
#         run: sudo apt update && sudo apt install libcunit1-dev
#       - name: 'Testing'
#         run: |
#           cd BuildCI
#           chmod +x *
#           ctest -V

#   cover_linux:
#     runs-on: ubuntu-latest
#     needs: [build_linux, test_linux]
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/download-artifact@v1
#         with:
#           name: binaries
#           path: BuildCI/
#       - name: 'Packages'
#         run: sudo apt update && sudo apt install gcovr libcunit1-dev
#       - name: 'Coverage'
#         run: |
#           cd BuildCI
#           chmod +x *
#           make cover_html                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
#       - uses: actions/upload-artifact@v1
#         with:
#           name: binaries
#           path: BuildCI/Coverage
